sudo: required

language: python

services:
  - docker

before_install:
  - bash dependencies.sh
  - bash toolbox.sh

script:
  - bash check.sh

# addons:
#   apt:
#     packages:
#       - oracle-java8-installer
