sudo: false
language: python

env:
  global:
    - CACHE_DIR=$HOME/.cache

services:
  - docker

before_install:
  - bash dependencies.sh
  - bash toolbox.sh

script:
  - bash check.sh

cache:
  directories:
    - $CACHE_DIR

# addons:
#   apt:
#     packages:
#       - oracle-java8-installer
