version: 2
jobs:
  build:
    environment:
      - WORKDIR: "/circleci"
      - CACHE_DIR: "/.cache"
      - CACHE_KEY: "app-cache"
    
    working_directory: "/circleci"
    
    docker:
      - image: viniciusam/utplsql

    steps:
      - checkout
      - setup_docker_engine

      - restore_cache:
          key: ${CACHE_KEY}

      - run:
          name: Download, Build and Save Oracle 12c to Cache
          command: bash ${WORKDIR}/.circleci/build_oracle_12c.sh
      
      - save_cache:
          key: ${CACHE_KEY}
          paths:
            - ${CACHE_DIR}

      - run:
          name: Run Oracle 12c
          command: |
            docker load < ${CACHE_DIR}/oracle-12c.tar
            docker run -d --privileged --name oracle-12c -p 1521:1521 oracle-12c
            docker logs -f oracle-12c | grep -m 1 "DATABASE IS READY TO USE!" --line-buffered
